package component:networking-server@0.1.121;

interface packets {
    resource packet {
    constructor(raw: list<u8>);
    get-bytes: func() -> list<u8>;
    get-raw: func() -> list<u8>;
    set-bytes: func(raw: list<u8>);
  }
}

interface packet-manager {
  use packets.{packet};
  spawn-client: func(id: u32) -> packet;
  handle-packet: func(data: packet) -> packet;
}