// Generated by `wit-bindgen` 0.43.0. DO NOT EDIT!
#ifndef __CPP_GUEST_BINDINGS_EXAMPLE_H
#define __CPP_GUEST_BINDINGS_EXAMPLE_H
#include <cstdint>
#include <utility>
#include <wit-guest.h>
namespace exports {namespace example {wit::string HelloWorld();
}}

#endif
