[package]
name = "rust-networking"
version = "0.1.0"
edition = "2024"
description = """
QUIC-based host component for testing WIT interfaces and async networking
"""

[profile.dev]
opt-level = 1
debug = true
codegen-units = 256
incremental = true

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5", default-features = false, features = ["derive", "std"] }


tokio = { version = "1.38", features = ["full"] }
quinn = "0.11.8"
rcgen = "0.14.3"
rustls = { version = "0.23.31", features = ["ring"]}

wasmtime = "33.0"
wasmtime-wasi = "33.0"

async-channel = "2.5.0"
futures = "0.3.31"
bytes = "1.10.1"
directories-next = "2.0.0"
url = "2.5.4"
env_logger = "0.11.8"

[features]
host-networking = []
client-networking = []

[[bin]]
name = "network-server"
path = "./src/bin/server.rs"
required-features = ["host-networking"]

[[bin]]
name = "network-client"
path = "./src/bin/client.rs"
required-features = ["client-networking"]
