package component:networking-client@0.1.0;

interface packets {
    resource packet {
    constructor(raw: list<u8>);
    get-bytes: func() -> list<u8>;
    get-raw: func() -> list<u8>;
    set-bytes: func(raw: list<u8>);
  }
}

interface packet-manager {
  use packets.{packet};
  handle-packet: func(data: packet) -> packet;
}